openapi: 3.0.4
info:
  title: QRCode REST OpenAPI 3.0 Specification
  description: REST Specification used in the QRCode Spring Boot App
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
servers:
  - url: http://localhost:9090/api/v1
tags:
  - name: QRCode
    description: Operation related to QR Code generation
paths:
  /qrcode/health:
    get:
      tags:
        - QRCode
      summary: REST health status
      description: Entrypoint that tests whether the REST is up and running or not.
      operationId: healthStatus
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
              example:
                status: ready
  /qrcode/generate:
    post:
      tags:
        - QRCode
      summary: Generates QR Code.
      description: Generates QR Code as array of bytes for the given URL.
      operationId: qrcodeGenerate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputData'
            example:
              url: "https://pdfobject.com/pdf/sample.pdf"
              size: 400
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BytesArray'
              example:
                output: "iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQAAAABRBrPYAAABWklEQVR4Xu3QQW7FMAgEUG7G1X2k3iBlBuNElvn5y6oaojhmeGxi1zf1Y3tyLLGtxLYS20psq7/PhrE8bj7MBy7xWalYw3AFgRiYzHvNxBqG2YwTsV+p2EdWJ44bi72xi1n2Yt+wNcx5djMVa5mxHKPHM1Oxjq0aSHGAPXKxI4sBRjxiCnM/Yh9YDqEGLRctY7GOJUQQbzokFCyxllnBifh3x6RiDSvHSZJM+RE7MxrMM2RfdiATO7KaOX1MYob2qkWxM4sBgqdaK2ItQ2yU1AxyPVuxhln9V2COGEXn3BA7MzQDkG8uVY4S61hOUt8LjkSsZ/Em5IrnnmGDodiRVcUUIb+1KtYztviZHtd48UGHk/tiZ8YGJxWH7Lgi1rP6nb42+MtnK/bGbL0cw+Im9sow8hmh6MUaVhjK0c4N3sU6Nv8kmaPDmDcqsTN7LbGtxLYS20psq//AfgFHoaFfQHsVsAAAAABJRU5ErkJggg=="
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: "Not able to generate QR Code"
components:
  schemas:
    InputData:
      required:
        - url
      type: object
      properties:
        url:
          description: URL of the target document used to generate the QR code image
          type: string
        size:
          description: the height and width in pixels of the resulting squared QR code image
          type: integer
          format: int32
    BytesArray:
      description: QR code image as bytes (string representation)
      type: object
      properties:
        output:
          type: string
          format: byte
    Error:
      description: error message
      type: object
      properties:
        message:
          type: string
      required:
        - message
    Status:
      description: liveness status of the REST application
      type: object
      properties:
        status:
          type: string
          enum:
            - ready
            - unavailable
      required:
        - status